const stylesActionTypes = {
    RETRIEDVED_STYLES_SETTINGS: "RETRIEDVED_STYLES_SETTINGS",
    UPDATED_STYLES_SETTINGS: "UPDATED_STYLES_SETTINGS",
    STYLES_SETTINGS_CLIENT_MODIFIED: "UPDATED_STYLES_SETTINGS",
    CHANGED_PORTAL_ID: "CHANGED_PORTAL_ID"
};

export default stylesActionTypes; 